services:
  - type: web
    name: evlin-backend
    env: python
    rootDir: evlin-backend
    region: oregon # adjust based on preference
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd evlin-backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false # Set this securely in the Render Dashboard
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_PUBLIC_BUCKET_NAME
        sync: false
