import Foundation
import SwiftUI

@MainActor
class AppSync {
    static let shared = AppSync()
    
    // Call this when the app starts or comes foreground, and after onboarding finishes
    func syncBackendData() async {
        do {
            let apiChildren = try await APIClient.shared.fetchChildren()
            
            // If backend is empty (no kids paired/created), nothing to sync yet
            guard let firstApiChild = apiChildren.first else {
                print("AppSync: No child found on backend yet.")
                return 
            }
            
            let childIdStr = firstApiChild.id
            
            // 1. Fetch Backend Data
            let rules = try await APIClient.shared.fetchRules(childId: childIdStr)
            let state = try await APIClient.shared.fetchState(childId: childIdStr)
            let apiTasks = try await APIClient.shared.fetchTasks(childId: childIdStr)
            let apiOccurrences = try await APIClient.shared.fetchOccurrences(childId: childIdStr)
            
            // 2. Map Rules
            var childRules: [ChildRule] = []
            childRules.append(ChildRule(
                id: "screen-time-limit",
                kind: .screenTimeLimit,
                icon: "sf:hourglass",
                title: "Screen Time Limit",
                detail: "\(formatMinutes(rules.dailyLimitMinutes)) per day",
                on: true
            ))
            
            if rules.downtimeEnabled {
                childRules.append(ChildRule(
                    id: "downtime",
                    kind: .downtime,
                    icon: "dark_mode",
                    title: "Downtime",
                    detail: "\(rules.downtimeStart ?? "8:00 PM") – \(rules.downtimeEnd ?? "7:00 AM")",
                    on: true
                ))
            }
            
            // 3. Map Tasks/Occurrences -> UI `ChildTask`
            var uiTasks: [ChildTask] = []
            for task in apiTasks {
                // Find today's occurrence (if generated by cron or dynamically)
                let occurrence = apiOccurrences.first(where: { $0.taskId == task.id })
                
                let uiState: TaskState
                if let occ = occurrence {
                    switch occ.status {
                    case "approved": uiState = .done
                    case "submitted": uiState = .review
                    case "rejected": uiState = .pending // Or an explicit rejected state if UI supports
                    default: uiState = .pending
                    }
                } else {
                    uiState = .pending
                }
                
                uiTasks.append(ChildTask(
                    id: task.id,
                    title: task.title,
                    state: uiState,
                    category: task.bucket,
                    description: task.instructions ?? "",
                    note: occurrence?.bypassNote,
                    dueDate: nil, // MVP: Treat all as today unless it's an advanced scheduled task
                    photoCount: task.submissionKind == "photo" ? 1 : 0,
                    repeats: task.recurrence
                ))
            }
            
            // 4. Update FamilyStore & TaskStore
            // Since the UI still heavily relies on the hardcoded "liam" ID in navigation and bindings,
            // we keep the ID as "liam" for the prototype but overwrite its contents with the real backend data.
            TaskStore.binding(for: "liam").wrappedValue = uiTasks
            
            let childStatus: ChildStatus = uiTasks.contains(where: { $0.state == .pending }) ? .lockedTasks : .unlocked
            
            if let existingChild = FamilyStore.children.first {
                existingChild.name = firstApiChild.name
                existingChild.rules = childRules
                existingChild.dailyLimitMin = rules.dailyLimitMinutes
                existingChild.tasksTotal = uiTasks.count
                existingChild.tasksDone = uiTasks.filter { $0.state == .done }.count
                existingChild.status = state.manualLock ? .locked : childStatus
            } else {
                // If it was somehow empty, inject the real child using the mock ID for UI compat
                FamilyStore.children.append(Child(
                    id: "liam", name: firstApiChild.name, age: 10, dailyLimitMin: rules.dailyLimitMinutes,
                    color: childColorPalette[0], status: childStatus,
                    timeLeft: formatMinutes(rules.dailyLimitMinutes), timePct: 100, usageTodayMin: 0,
                    tasksDone: uiTasks.filter { $0.state == .done }.count, tasksTotal: uiTasks.count, subtitle: "No tasks yet",
                    devices: demoDevice(firstApiChild.name)
                ))
            }
            
            print("AppSync: Successfully synced backend data into UI state!")
            
        } catch {
            print("AppSync Failed: \(error.localizedDescription)")
        }
    }
}
